### PR TITLE
Add GH actions

### PR DESCRIPTION
**Pull request by Licenser**
WIP add github actions.

3 actions:

1) clippy
2) rustfmt
3) tests + miri

### CODE REVIEW

**Comment by Licenser** [comment]
they can be seen running here: https://github.com/Licenser/beef/actions

I included a rustfmt one which currently fails, I figured it's nice as a demo but I don't mind removing it again.

**Comment by maciejhirsz** [comment]
This looks pretty good to me, having tests on more than one platform definitely helps. I don't know that we need to test with avx here, I doubt there are any chances for auto-vectorization to work here :P.

As for fmt, I'm not super hot for it (#17), I'd be fine if we can have the tests macro not have two levels of indention for no good reason in lib.rs, if you can either `#[rustfmt::skip]` that or disable it in the CI I think that would be best.

**Comment by Licenser** [comment]
Added the ignore + formated the rest :)

**Comment by maciejhirsz** [comment]
Cheers!

**Comment by maciejhirsz** [comment]
Um, now I'm looking at it, it's only running `cargo build`, except for miri? :P

**Comment by Licenser** [comment]
🤦‍♂ let me fix that -.-

**Pull request merged**
